TOP=$(HOME)/linwx
BASE_OMNI_TREE=$(HOME)
INSTALL=$(HOME)/bin/scripts/install-sh

# you must modify follows for compile you program correctly.

VPATH=tools/pkg4c
CURRENT=tools/pkg4c

# modify end.

include $(TOP)/mk/beforeauto.mk
include ./dir.mk
include $(TOP)/mk/afterauto.mk
